import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Footer.jsx
// Importe os ícones do Lucide React que vai usar
import { Github, Linkedin, Twitter, Dribbble } from 'lucide-react';
const Footer = () => {
    const currentYear = new Date().getFullYear(); // Para o ano dinâmico
    return (_jsx("footer", { className: "bg-gray-900 text-white py-12", children: _jsxs("div", { className: "container mx-auto px-6", children: [_jsxs("div", { className: "flex flex-col md:flex-row justify-between items-center", children: [_jsxs("div", { className: "mb-8 md:mb-0 text-center md:text-left", children: [_jsx("a", { href: "/", className: "text-3xl font-bold text-white hover:text-gray-200 transition-colors", children: "Ginovaldo Cumbe " }), _jsx("p", { className: "mt-2 text-gray-400 max-w-md mx-auto md:mx-0 leading-relaxed", children: "Construir experi\u00EAncias digitais excecionais com c\u00F3digo limpo, eficiente e escal\u00E1vel." })] }), _jsxs("div", { className: "flex flex-col items-center md:items-end", children: [_jsxs("div", { className: "flex space-x-4 mb-4", children: [_jsx("a", { href: "https://github.com/o-ginovaldo" // Substitua pelo seu link GitHub real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "GitHub", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: _jsx(Github, { size: 20 }) }), _jsx("a", { href: "https://linkedin.com/in/o-ginovaldo" // Substitua pelo seu link LinkedIn real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "LinkedIn", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: _jsx(Linkedin, { size: 20 }) }), _jsx("a", { href: "https://twitter.com/o-ginovaldo" // Substitua pelo seu link Twitter/X real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "Twitter", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: _jsx(Twitter, { size: 20 }) }), _jsx("a", { href: "https://dribbble.com/o-ginovaldo" // Substitua pelo seu link Dribbble real (se tiver)
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "Dribbble", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: _jsx(Dribbble, { size: 20 }) })] }), _jsxs("p", { className: "text-gray-500 text-sm mt-2", children: ["\u00A9 ", currentYear, " Ginovaldo Cumbe. Todos os direitos reservados."] })] })] }), _jsxs("div", { className: "mt-12 pt-8 border-t border-gray-800 flex flex-col md:flex-row justify-between items-center", children: [_jsxs("div", { className: "flex flex-wrap justify-center md:justify-start gap-x-6 gap-y-2 mb-4 md:mb-0", children: [_jsx("a", { href: "/politica-de-privacidade", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Pol\u00EDtica de Privacidade" }), _jsx("a", { href: "/termos-de-servico", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Termos de Servi\u00E7o" }), _jsx("a", { href: "/politica-de-cookies", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Pol\u00EDtica de Cookies" })] }), _jsx("div", { className: "flex space-x-4" })] })] }) }));
};
export default Footer;
