"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
// src/components/Footer.jsx
// Importe os ícones do Lucide React que vai usar
var lucide_react_1 = require("lucide-react");
var Footer = function () {
    var currentYear = new Date().getFullYear(); // Para o ano dinâmico
    return ((0, jsx_runtime_1.jsx)("footer", { className: "bg-gray-900 text-white py-12", children: (0, jsx_runtime_1.jsxs)("div", { className: "container mx-auto px-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col md:flex-row justify-between items-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "mb-8 md:mb-0 text-center md:text-left", children: [(0, jsx_runtime_1.jsx)("a", { href: "/", className: "text-3xl font-bold text-white hover:text-gray-200 transition-colors", children: "Ginovaldo Cumbe " }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-gray-400 max-w-md mx-auto md:mx-0 leading-relaxed", children: "Construir experi\u00EAncias digitais excecionais com c\u00F3digo limpo, eficiente e escal\u00E1vel." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col items-center md:items-end", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-4 mb-4", children: [(0, jsx_runtime_1.jsx)("a", { href: "https://github.com/o-ginovaldo" // Substitua pelo seu link GitHub real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "GitHub", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Github, { size: 20 }) }), (0, jsx_runtime_1.jsx)("a", { href: "https://linkedin.com/in/o-ginovaldo" // Substitua pelo seu link LinkedIn real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "LinkedIn", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Linkedin, { size: 20 }) }), (0, jsx_runtime_1.jsx)("a", { href: "https://twitter.com/o-ginovaldo" // Substitua pelo seu link Twitter/X real
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "Twitter", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Twitter, { size: 20 }) }), (0, jsx_runtime_1.jsx)("a", { href: "https://dribbble.com/o-ginovaldo" // Substitua pelo seu link Dribbble real (se tiver)
                                            , target: "_blank", rel: "noopener noreferrer", "aria-label": "Dribbble", className: "w-10 h-10 flex items-center justify-center bg-gray-800 text-gray-400 rounded-full hover:bg-blue-600 hover:text-white transition-all duration-300 transform hover:scale-105", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Dribbble, { size: 20 }) })] }), (0, jsx_runtime_1.jsxs)("p", { className: "text-gray-500 text-sm mt-2", children: ["\u00A9 ", currentYear, " Ginovaldo Cumbe. Todos os direitos reservados."] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 pt-8 border-t border-gray-800 flex flex-col md:flex-row justify-between items-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-wrap justify-center md:justify-start gap-x-6 gap-y-2 mb-4 md:mb-0", children: [(0, jsx_runtime_1.jsx)("a", { href: "/politica-de-privacidade", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Pol\u00EDtica de Privacidade" }), (0, jsx_runtime_1.jsx)("a", { href: "/termos-de-servico", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Termos de Servi\u00E7o" }), (0, jsx_runtime_1.jsx)("a", { href: "/politica-de-cookies", className: "text-gray-400 hover:text-white transition-colors text-sm", children: "Pol\u00EDtica de Cookies" })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex space-x-4" })] })] }) }));
};
exports.default = Footer;
